listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/secrets/passwords
acl_file /mosquitto/secrets/acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 30
autosave_on_changes true
persistent_client_expiration 14d

max_packet_size 1048576
max_queued_messages 10000
max_inflight_messages 20

sys_interval 10
connection_messages true
log_dest stdout
log_timestamp true
log_type error
log_type warning
log_type notice
log_type information